# rubocop:disable all

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/conversations', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Conversation. As you add validations to Conversation, be sure to
  # adjust the attributes here as well.
  current_user = User.first_or_create!(name: 'user', username: 'user', email: 'user@example.com', password: 'password',
                                       password_confirmation: 'password')

  let(:valid_attributes) do
    {
      'topic' => 'topic',
      'private' => false
    }
  end

  let(:invalid_attributes) do
    {
      'id' => 'a',
    }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      sign_in(current_user)
      Conversation.create! valid_attributes
      get conversations_url
      expect(response).to be_successful
    end
  end





  describe 'GET /edit' do
    it 'renders a successful response' do
      conversation = Conversation.create! valid_attributes
      get edit_conversation_url(conversation)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Conversation' do
        expect do
          sign_in(current_user)
          post conversations_url, params: { conversation: valid_attributes }
        end.to change(Conversation, :count).by(1)
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Conversation' do
        expect do
          post conversations_url, params: { conversation: invalid_attributes }
        end.to change(Conversation, :count).by(0)
      end
    end
  end


  describe 'DELETE /destroy' do
    it 'destroys the requested conversation' do
      sign_in(current_user)

      conversation = Conversation.create! valid_attributes
      expect do
        delete conversation_url(conversation)
      end.to change(Conversation, :count).by(-1)
    end
  end
end
