# rubocop:disable all

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/conversation_users', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ConversationUser. As you add validations to ConversationUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      ConversationUser.create! valid_attributes
      get convesation_users_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      convesation_user = ConversationUser.create! valid_attributes
      get convesation_user_url(convesation_user)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_convesation_user_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      convesation_user = ConversationUser.create! valid_attributes
      get edit_convesation_user_url(convesation_user)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new ConversationUser' do
        expect do
          post convesation_users_url, params: { conversation_user: valid_attributes }
        end.to change(ConversationUser, :count).by(1)
      end

      it 'redirects to the created conversation_user' do
        post convesation_users_url, params: { conversation_user: valid_attributes }
        expect(response).to redirect_to(convesation_user_url(ConversationUser.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new ConversationUser' do
        expect do
          post convesation_users_url, params: { conversation_user: invalid_attributes }
        end.to change(ConversationUser, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post convesation_users_url, params: { conversation_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested conversation_user' do
        convesation_user = ConversationUser.create! valid_attributes
        patch convesation_user_url(convesation_user), params: { conversation_user: new_attributes }
        convesation_user.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the conversation_user' do
        convesation_user = ConversationUser.create! valid_attributes
        patch convesation_user_url(convesation_user), params: { conversation_user: new_attributes }
        convesation_user.reload
        expect(response).to redirect_to(convesation_user_url(convesation_user))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        convesation_user = ConversationUser.create! valid_attributes
        patch convesation_user_url(convesation_user), params: { conversation_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested conversation_user' do
      convesation_user = ConversationUser.create! valid_attributes
      expect do
        delete convesation_user_url(convesation_user)
      end.to change(ConversationUser, :count).by(-1)
    end

    it 'redirects to the conversation_users list' do
      convesation_user = ConversationUser.create! valid_attributes
      delete convesation_user_url(convesation_user)
      expect(response).to redirect_to(convesation_users_url)
    end
  end
end
