# rubocop:disable all

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/retweets', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Retweet. As you add validations to Retweet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Retweet.create! valid_attributes
      get retweets_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      retweet = Retweet.create! valid_attributes
      get retweet_url(retweet)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_retweet_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      retweet = Retweet.create! valid_attributes
      get edit_retweet_url(retweet)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Retweet' do
        expect do
          post retweets_url, params: { source_id: valid_attributes }
        end.to change(Retweet, :count).by(1)
      end

      it 'redirects to the created retweet' do
        post retweets_url, params: { source_id: valid_attributes }
        expect(response).to redirect_to(retweet_url(Retweet.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Retweet' do
        expect do
          post retweets_url, params: { source_id: invalid_attributes }
        end.to change(Retweet, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post retweets_url, params: { source_id: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested retweet' do
        retweet = Retweet.create! valid_attributes
        patch retweet_url(retweet), params: { source_id: new_attributes }
        retweet.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the retweet' do
        retweet = Retweet.create! valid_attributes
        patch retweet_url(retweet), params: { source_id: new_attributes }
        retweet.reload
        expect(response).to redirect_to(retweet_url(retweet))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        retweet = Retweet.create! valid_attributes
        patch retweet_url(retweet), params: { source_id: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested retweet' do
      retweet = Retweet.create! valid_attributes
      expect do
        delete retweet_url(retweet)
      end.to change(Retweet, :count).by(-1)
    end

    it 'redirects to the retweets list' do
      retweet = Retweet.create! valid_attributes
      delete retweet_url(retweet)
      expect(response).to redirect_to(retweets_url)
    end
  end
end
